drop table if exists mh_admin;
drop table if exists mh_banner;
drop table if exists mh_user_account;
drop table if exists mh_user_profile;
drop table if exists mh_house;
drop table if exists mh_image;
drop table if exists mh_random_user;

create table mh_admin (
	id bigint generated by default as identity,
	login_name varchar(64) not null unique,
	name varchar(64) not null,
	password varchar(255) not null,
	salt varchar(64) not null,
	roles varchar(255) not null,
	register_date timestamp not null,
	primary key (id)
);

create table mh_banner (
	id bigint generated by default as identity,
	url varchar(128) not null,
	thumbnail varchar(128),
	uid bigint not null,
	sort int default(0),
	create_time long not null,
	primary key (id) 
);

create table mh_user_account (
    id bigint generated by default as identity,
    type smallint not null,
    username varchar(64) not null,
    password varchar(64) not null,
    salt varchar(64) not null,
    primary key (id)
);

create table mh_user_profile (
    id bigint generated by default as identity,
    nickname varchar(64) not null,
    telephone varchar(64) not null,
    realname varchar(64) not null,
    email varchar(64) not null,
    company varchar(1024) not null,
    avatar varchar(64) not null,
    create_time bigint not null default(0),
    primary key (id)
);

create table mh_house (
    id bigint generated by default as identity,
    code varchar(64) not null,
    address varchar(255),
    price int default(0),
    area int default(0),
    bedrooms varchar(64),
    open_time bigint default(0),
    create_time bigint default(0),
    last_update_time bigint default(0),
    lastd2upload_time bigint default(0),
    lastd3upload_time bigint default(0),
    bg_music varchar(64),
    cover_img varchar(128),
    package_url varchar(128),
    photographer varchar(128),
    youtube varchar(128),
    description varchar(1024),
    uid bigint not null,
    primary key (id)
);

create table mh_image (
    id bigint generated by default as identity,
    type smallint not null,
    url varchar(128),
    thumbnail varchar(128),
    name varchar(64) not null,
    sort int not null default(0),
    display tinyint not null default(1),
    hid bigint not null,
    primary key (id)
);

create table mh_random_user (
    id bigint generated by default as identity,
    page_index int not null,
    page_pos int not null,
    uid bigint not null,
    primary key (id)
);